#heroku config:set PROD_MONGODB=mongodb://hmidbuser:hmi141209@ds243931.mlab.com:43931/heaven_calendar
mlab:
  db.host: ds243931.mlab.com
  db.name: heaven_calendar
  db.user: hmidbuser
  db.port: 43931
  db.password: hmi141209
  api.key: pSg2YGo6Qc53wzwsHVfJrEpB7jaPqMa6

spring:
  data.mongodb.uri: mongodb://hmidbuser:hmi141209@ds243931.mlab.com:43931/heaven_calendar
  servlet.multipart.enabled: true
  servlet.multipart.file-size-threshold: 2KB
  servlet.multipart.max-file-size: 200MB
  servlet.multipart.max-request-size: 215MB
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

application:
  key: 2c060457dbaaf60054c1660c1502d45e

access:
  token: 1ecf8afebc37821645280cde72a2bd293781820444cc272281f5f5444e5cb77f


file:
  upload-dir=./hcalendar-uploads

jwt:
  header: Authorization
  expirationInSecond : 86400
  secret: YKscj]TyorRICKk]aNXrW4]YK9_i8Lp_v<@=f=AE:c6qw4JK5I>ahts:2G=0kceY
  issuedBy: HEAVEN-CALENDAR
